# PAYMENTS CLEANING

In [ ]:
import pandas as pd
payments = pd.read_csv("../Data/sanlam_raw_payments.csv")

payments.head()

In [2]:
# Check to see if the transaction date has any NA values 
payments['transaction_date'].isna().sum()

np.int64(162)

In [3]:
# Step 1: Create a parser for the known formats
def parse_transaction_date(date_str):
    if pd.isna(date_str):
        return pd.NaT

    date_str = str(date_str).strip()

    try:
        # DD/MM/YYYY
        if '/' in date_str and len(date_str.split('/')[0]) == 2:
            return pd.to_datetime(date_str, format='%d/%m/%Y')

        # MM-DD-YYYY
        elif '-' in date_str and len(date_str.split('-')[0]) == 2:
            return pd.to_datetime(date_str, format='%m-%d-%Y')

        # YYYY-MM-DD
        elif len(date_str.split('-')[0]) == 4:
            return pd.to_datetime(date_str, format='%Y-%m-%d')

        # YYYY/MM/DD
        elif len(date_str.split('/')[0]) == 4:
            return pd.to_datetime(date_str, format='%Y/%m/%d')

        return pd.NaT

    except:
        return pd.NaT

In [10]:
# Step 2: Parse the dates
payments['parse_transaction_date'] = (
    payments['transaction_date']
    .apply(parse_transaction_date)
)

In [11]:
payments.head()

,source_row_id,transaction_ref,policy_id,client_id,transaction_date,amount,transaction_type,currency,payment_method,payment_status,source_system,parse_transaction_date
0,SPAY-0000000001,TX-S-0000000001,POL000003392,CL00007794,2022-11-15,"1,826.09",Commission,R,NaN,Reversed,LegacyLedger,2022-11-15
1,SPAY-0000000002,TX-S-0000000002,POL000000796,CL00008081,2022-10-23,"R -7,370.85",Refund,ZAR,EFT,success,PaymentsHub,2022-10-23
2,SPAY-0000000003,TX-S-0000000003,POL000003511,CL00007728,10/03/2025,"R 4,318.19",EFT,ZAR,Card,Paid,LegacyLedger,2025-03-10
3,SPAY-0000000004,TX-S-0000000004,POL000012172,CL00001221,2025/03/21,"R 4,114.14\r\n",Debit Order,R,EFT,Successful,PaymentsHub,2025-03-21
4,SPAY-0000000005,TX-S-0000000005,POL000014430,CL00008773,2025/04/23,"ZAR 21,151.57",EFT,ZAR,Debit Order,Reversed,BankFeed,2025-04-23

In [ ]:
# Step 3: Find malformed dates
bad_dates = payments[
    payments['transaction_date'].notna() &
    payments['parse_transaction_date'].isna()
]

In [18]:
# Step 4: Count malformed dates
bad_dates.shape[0]

454

In [13]:
#Step 5
payments['transaction_date_std'] = (
    payments['parse_transaction_date']
    .dt.strftime('%d-%m-%Y')
)

In [15]:
payments.columns.tolist()

['source_row_id',
 'transaction_ref',
 'policy_id',
 'client_id',
 'transaction_date',
 'amount',
 'transaction_type',
 'currency',
 'payment_method',
 'payment_status',
 'source_system',
 'parse_transaction_date',
 'transaction_date_std']

In [32]:
payments.head(30)

,source_row_id,transaction_ref,policy_id,transaction_date_new,client_id,amount,transaction_type,currency,payment_method,payment_status,source_system
0,SPAY-0000000001,TX-S-0000000001,POL000003392,2022-11-15,CL00007794,"1,826.09",Commission,R,NaN,Reversed,LegacyLedger
1,SPAY-0000000002,TX-S-0000000002,POL000000796,2022-10-23,CL00008081,"R -7,370.85",Refund,ZAR,EFT,success,PaymentsHub
2,SPAY-0000000003,TX-S-0000000003,POL000003511,2025-03-10,CL00007728,"R 4,318.19",EFT,ZAR,Card,Paid,LegacyLedger
3,SPAY-0000000004,TX-S-0000000004,POL000012172,2025-03-21,CL00001221,"R 4,114.14\r\n",Debit Order,R,EFT,Successful,PaymentsHub
4,SPAY-0000000005,TX-S-0000000005,POL000014430,2025-04-23,CL00008773,"ZAR 21,151.57",EFT,ZAR,Debit Order,Reversed,BankFeed
5,SPAY-0000000006,TX-S-0000000006,POL000008647,2025-03-09,CL00000156,NaN,Premium,USD,NaN,Failed,BankFeed
6,SPAY-0000000007,TX-S-0000000007,POL000000436,2024-06-23,CL00003805,"(-24,653.54)",Reversal,R,Cash,Successful,PaymentsHub
7,SPAY-0000000008,TX-S-0000000008,POL000024244,2022-05-31,CL00000252,5285.68,Premium,ZAR,Cash,Paid,PaymentsHub
8,SPAY-0000000009,TX-S-0000000009,POL000012945,2021-03-31,CL00007328,"20,646.63",Premium,ZAR,Debit Order,Reversed,LegacyLedger
9,SPAY-0000000010,TX-S-0000000010,POL000010985,2025-10-10,CL00004931,"ZAR -21,763.22",Commission Reversal,R,Card,Successful,BankFeed
10,SPAY-0000000011,TX-S-0000000011,POL000021474,2021-10-10,CL00008120,"ZAR -1,857.93",Commission Reversal,ZAR,Cash,Pending,BankFeed
11,SPAY-0000000012,TX-S-0000000012,POL000019827,2020-06-12,CL00007205,19337.71,Premium,ZAR,Cash,Pending,LegacyLedger
12,SPAY-0000000013,TX-S-0000000013,POL000003209,2025-02-10,CL00002583,20248.04,EFT,USD,Cash,Pending,PaymentsHub
13,SPAY-0000000014,TX-S-0000000014,POL000002372,2020-10-28,CL00000480,12202.70,Commission,USD,Debit Order,Pending,PaymentsHub
14,SPAY-0000000015,TX-S-0000000015,POL000009560,2021-11-11,CL00002401,"1.159,58",Commission,ZAR,Card,Paid,PaymentsHub
15,SPAY-0000000016,TX-S-0000000016,POL000021175,2022-05-17,CL00011783,"8.442,91",Debit Order,ZAR,Debit Order,Failed,BankFeed
16,SPAY-0000000017,TX-S-0000000017,MISSING-859967,2022-09-06,CL00001008,"R 14,281.58",EFT,R,EFT,Pending,LegacyLedger
17,SPAY-0000000018,TX-S-0000000018,POL000016867,2023-05-03,CL00009428,"7.194,80",Debit Order,ZAR,NaN,Successful,LegacyLedger
18,SPAY-0000000019,TX-S-0000000019,POL000022103,2021-03-15,CL00011751,"-9.282,07",Refund,ZAR,NaN,Failed,PaymentsHub
19,SPAY-0000000020,TX-S-0000000020,MISSING-584620,2022-03-22,CL00006573,"R 11,316.51",EFT,ZAR,Debit Order,success,BankFeed
20,SPAY-0000000021,TX-S-0000000021,POL000006668,2022-07-19,CL00011648,R --,Debit Order,R,EFT,Paid,BankFeed
21,SPAY-0000000022,TX-S-0000000022,POL000012813,2026-01-12,CL00000541,"R 20,240.22",Commission,ZAR,Debit Order,Failed,LegacyLedger
22,SPAY-0000000023,TX-S-0000000023,POL000025667,2025-10-30,CL00001250,"R 13,341.06",EFT,ZAR,Debit Order,Failed,LegacyLedger
23,SPAY-0000000024,TX-S-0000000024,POL000018254,2025-12-09,CL00002849,"18,967.27",EFT,ZAR,Debit Order,Reversed,LegacyLedger
24,SPAY-0000000025,TX-S-0000000025,POL000020453,2024-06-22,CL00002590,"8.295,99",Premium,R,EFT,Paid,PaymentsHub
25,SPAY-0000000026,TX-S-0000000026,POL000001450,2023-03-23,CL00007473,"3,339.97",Premium,ZAR,EFT,Failed,PaymentsHub
26,SPAY-0000000027,TX-S-0000000027,POL000022074,2025-09-02,CL00011221,"16,581.95",Premium,ZAR,Card,Pending,PaymentsHub
27,SPAY-0000000028,TX-S-0000000028,POL000001597,2024-09-02,CL00011077,"3.879,59",Commission,USD,Cash,success,LegacyLedger
28,SPAY-0000000029,TX-S-0000000029,POL000006735,2023-01-14,CL00004652,"R 6,003.02",Premium,R,EFT,Successful,PaymentsHub
29,SPAY-0000000030,TX-S-0000000030,POL000012950,2023-08-12,CL00011952,"ZAR 4,796.07",EFT,ZAR,Card,success,BankFeed

In [ ]:
#Rename the transaction_date_std to transaction_date_new
payments.rename(columns={'transaction_date_std': 'transaction_date_new'}, inplace=True)

In [23]:
# Remove the parse_transaction_date coloumn 
payments.drop(columns=['parse_transaction_date'], inplace=True)

In [25]:
# Remove the transaction_date coloumn (original)
payments.drop(columns=['transaction_date'], inplace=True)

In [27]:
cols = payments.columns.tolist()

# Remove the column from its current position
cols.remove('transaction_date_new')

# Insert it into the 4th position
cols.insert(3, 'transaction_date_new')

# Reorder the dataframe
payments = payments[cols]

In [31]:
payments.dtypes

source_row_id                      str
transaction_ref                    str
policy_id                          str
transaction_date_new    datetime64[us]
client_id                          str
amount                             str
transaction_type                   str
currency                           str
payment_method                     str
payment_status                     str
source_system                      str
dtype: object

In [30]:
# Convert string to datetime 
payments['transaction_date_new'] = pd.to_datetime(
    payments['transaction_date_new'],
    format='%d-%m-%Y',
    errors='coerce'
)

In [ ]:
## Check the malformed dates (QUARTINIE ALL 616 ROWS)
payments['transaction_date_new'].isna().sum()

np.int64(616)

In [ ]:
# Check the currency distinct values 
payments['currency'].unique().tolist()

['ZAR', 'USD']

In [39]:
payments['currency'] = payments['currency'].replace('R', 'ZAR')

In [ ]:
# Check the distinct values for payment method. 
payments['payment_method'].unique().tolist()

[nan, 'EFT', 'Card', 'Debit Order', 'Cash']

In [46]:
payments['payment_method'].isna().sum()

np.int64(12020)

In [47]:
# Set 1202payment_method0 payment method to "Unknown"
payments['payment_method'] = payments['payment_method'].fillna('Unknown')

In [48]:
payments['payment_method'].head(10)

0        Unknown
1            EFT
2           Card
3            EFT
4    Debit Order
5        Unknown
6           Cash
7           Cash
8    Debit Order
9           Card
Name: payment_method, dtype: str

In [51]:
payments['payment_method'].unique().tolist()

['Unknown', 'EFT', 'Card', 'Debit Order', 'Cash']

In [ ]:
#Remove trailling spaces and whitespaces. 
payments['payment_method'] = payments['payment_method'].str.strip()

In [57]:
payments.head(10)

,source_row_id,transaction_ref,policy_id,transaction_date_new,client_id,amount,transaction_type,currency,payment_method,payment_status,source_system
0,SPAY-0000000001,TX-S-0000000001,POL000003392,2022-11-15,CL00007794,"1,826.09",Commission,ZAR,Unknown,Reversed,LegacyLedger
1,SPAY-0000000002,TX-S-0000000002,POL000000796,2022-10-23,CL00008081,"-7,370.85",Refund,ZAR,EFT,success,PaymentsHub
2,SPAY-0000000003,TX-S-0000000003,POL000003511,2025-03-10,CL00007728,"4,318.19",EFT,ZAR,Card,Paid,LegacyLedger
3,SPAY-0000000004,TX-S-0000000004,POL000012172,2025-03-21,CL00001221,"4,114.14",Debit Order,ZAR,EFT,Successful,PaymentsHub
4,SPAY-0000000005,TX-S-0000000005,POL000014430,2025-04-23,CL00008773,"21,151.57",EFT,ZAR,Debit Order,Reversed,BankFeed
5,SPAY-0000000006,TX-S-0000000006,POL000008647,2025-03-09,CL00000156,NaN,Premium,USD,Unknown,Failed,BankFeed
6,SPAY-0000000007,TX-S-0000000007,POL000000436,2024-06-23,CL00003805,"(-24,653.54)",Reversal,ZAR,Cash,Successful,PaymentsHub
7,SPAY-0000000008,TX-S-0000000008,POL000024244,2022-05-31,CL00000252,5285.68,Premium,ZAR,Cash,Paid,PaymentsHub
8,SPAY-0000000009,TX-S-0000000009,POL000012945,2021-03-31,CL00007328,"20,646.63",Premium,ZAR,Debit Order,Reversed,LegacyLedger
9,SPAY-0000000010,TX-S-0000000010,POL000010985,2025-10-10,CL00004931,"-21,763.22",Commission Reversal,ZAR,Card,Successful,BankFeed

In [ ]:
# Check if the coloumns contain R or ZAR 
payments[
    payments['amount'].astype(str).str.contains('R|ZAR', na=False)
]

In [56]:
#Replace the R and ZAR from amounts 
payments['amount'] = payments['amount'].str.replace('ZAR', '', regex=False)
payments['amount'] = payments['amount'].str.replace('R', '', regex=False)
payments['amount'] = payments['amount'].str.strip()

In [ ]:
#Check the distinct values in transcation type
payments['transaction_type'].unique().tolist()

['Commission',
 'Refund',
 'EFT',
 'Debit Order',
 'Premium',
 'Reversal',
 'Commission Reversal']

In [ ]:
#Display the value counts for each transaction type
payments['transaction_type'].value_counts(dropna=False)

transaction_type
Premium                18015
Commission             12024
Debit Order            11952
EFT                     7741
Reversal                4766
Commission Reversal     3103
Refund                  2399
Name: count, dtype: int64