# REVIEWING DATASETS

In [84]:
import pandas as pd
policy = pd.read_csv("../raw_data/sanlam_raw_policies.csv")

In [85]:
policy.head(10)

,source_row_id,policy_id,client_id,advisor_id,product_code,product_line,inception_date,end_date,annual_premium,sum_assured,policy_status,currency,source_system
0,SP-000000001,POL000000001,MISSING-763321,ADV000276,WEALTH,Wealth Investment,05/06/2022,04/06/2027,33254.23,"6.578.229,57",In Force,ZAR,WealthCore
1,SP-000000002,POL000000002,CL00011475,ADV000543,RA,Retirement Annuity,2021-09-05,2031/09/03,"ZAR 40,947.57","9,867,321.34",Lapsed,ZAR,WealthCore
2,SP-000000003,POL000000003,CL00004560,ADV000245,LIFE,Life Cover,2021/07/11,07-10-2026,46022.97,"R 7,841,284.09",In Force,ZAR,WealthCore
3,SP-000000004,POL000000004,CL00010896,ADV000588,WEALTH,Wealth Investment,07-23-2023,2033/07/20,"38.998,85","1,450,285.20",Unknown,R,LegacyLifeA
4,SP-000000005,POL000000005,CL00011016,ADV000019,RA,Retirement Annuity,2020-06-16,06-16-2021,"ZAR 21,239.96","R 1,396,051.35",Unknown,zar,WealthCore
5,SP-000000006,POL000000006,CL00003284,ADV000482,LIFE,Life Cover,11-06-2022,31/31/2024,"29.263,37","1.463.022,54",INFORCE,zar,LegacyLifeA
6,SP-000000007,POL000000007,CL00003297,ADV000489,LIFE,Life Cover,2019/03/15,2024-03-13,"39.059,96","10,957,534.54",Lapsed,ZAR,LegacyLifeA
7,SP-000000008,POL000000008,CL00009149,ADV000383,LIFE,Life Cover,18/06/2022,2027-06-17,"ZAR 19,717.92","5.226.636,62",Lapsed,zar,WealthCore
8,SP-000000009,POL000000009,CL00000846,ADV000518,LIFE,Life Cover,2022-06-16,2027/06/15,"ZAR 31,571.46","3,472,995.45",Lapsed,zar,LegacyLifeA
9,SP-000000010,POL000000010,CL00010149,ADV000500,LIFE,Life Cover,11-17-2022,2042/11/12,"44,001.26","R 10,854,659.95",Lapsed,ZAR,LegacyLifeA

In [86]:
policy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26000 entries, 0 to 25999
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   source_row_id   26000 non-null  object
 1   policy_id       26000 non-null  object
 2   client_id       26000 non-null  object
 3   advisor_id      26000 non-null  object
 4   product_code    26000 non-null  object
 5   product_line    26000 non-null  object
 6   inception_date  25919 non-null  object
 7   end_date        25948 non-null  object
 8   annual_premium  25901 non-null  object
 9   sum_assured     25928 non-null  object
 10  policy_status   26000 non-null  object
 11  currency        26000 non-null  object
 12  source_system   26000 non-null  object
dtypes: object(13)
memory usage: 2.6+ MB

In [87]:
profiling = policy.nunique().reset_index()
profiling.columns = ["Column", "Distinct_Values"]
profiling

            Column  Distinct_Values
0    source_row_id            26000
1        policy_id            26000
2        client_id            11050
3       advisor_id             1254
4     product_code                3
5     product_line                6
6   inception_date            11229
7         end_date            18325
8   annual_premium            25780
9      sum_assured            25852
10   policy_status                6
11        currency                3
12   source_system                3

In [88]:
policy['policy_status'].unique()

array(['In Force', 'Lapsed', 'Unknown', 'INFORCE', 'Cancelled', 'Active'],
      dtype=object)

In [89]:
policy['product_code'].unique()

array(['WEALTH', 'RA', 'LIFE'], dtype=object)

In [90]:
policy.isnull().sum()

source_row_id      0
policy_id          0
client_id          0
advisor_id         0
product_code       0
product_line       0
inception_date    81
end_date          52
annual_premium    99
sum_assured       72
policy_status      0
currency           0
source_system      0
dtype: int64

In [91]:
policy.duplicated().sum()

np.int64(0)

In [92]:
#Checking for consistency.
policy['sum_assured'].value_counts().head(10)

sum_assured
R --               41
not recorded       37
10,957,534.54       1
5.226.636,62        1
3,472,995.45        1
R 10,854,659.95     1
837.297,27          1
3,102,720.09        1
R 7,761,564.44      1
6,784,958.60        1
Name: count, dtype: int64

In [93]:
#%pip install openpyxl

In [94]:
clients = pd.read_excel("../raw_data/sanlam_raw_clients.csv.xlsx")

In [95]:
clients.head(10)

,source_row_id,client_id,synthetic_id_number,first_name,last_name,date_of_birth,gender,province,email,phone_placeholder,bank_account_placeholder,source_system
0,SC-000000001,CL00000001,SIM-ID-0929-000000001,Kabelo,Smith,27/01/1966,female,Western Cape,kabelo.smith.1@example.invalid,SIM-PHONE-929-00000001,SIM-ACCOUNT-000040,MergedBook
1,SC-000000002,CL00000002,SIM-ID-0929-000000002,Lwazi,Molefe,1984-11-25 00:00:00,Male,KwaZulu-Natal,lwazi.molefe.2@example.invalid,SIM-PHONE-929-00000002,SIM-ACCOUNT-000082,WealthCore
2,SC-000000003,CL00000003,SIM-ID-0929-000000003,Grace,Nkosi,1951-09-25 00:00:00,MALE,Limpopo,grace.nkosi.3@example.invalid,SIM-PHONE-929-00000003,SIM-ACCOUNT-000026,MergedBook
3,SC-000000004,CL00000004,SIM-ID-0929-000000004,Lwazi,Jacobs,15/10/1991,F,Western cape,lwazi.jacobs.4@example.invalid,SIM-PHONE-929-00000004,SIM-ACCOUNT-000063,LegacyLifeB
4,SC-000000005,CL00000005,SIM-ID-0929-000000005,Amina,Mahlangu,2003-10-07 00:00:00,female,Western Cape,amina.mahlangu.5@example.invalid,SIM-PHONE-929-00000005,SIM-ACCOUNT-000033,WealthCore
5,SC-000000006,CL00000006,SIM-ID-0929-000000006,David,Jacobs,1967-02-14 00:00:00,Unknown,gauteng,david.jacobs.6@example.invalid,SIM-PHONE-929-00000006,SIM-ACCOUNT-000003,LegacyLifeA
6,SC-000000007,CL00000007,SIM-ID-0929-000000007,Portia,Mabena,1952-11-04 00:00:00,female,Northern Cape,portia.mabena.7@example.invalid,SIM-PHONE-929-00000007,SIM-ACCOUNT-000076,LegacyLifeA
7,SC-000000008,CL00000008,SIM-ID-0929-000000008,Thandi,Mokoena,1961-02-20 00:00:00,F,Western cape,thandi.mokoena.8@example.invalid,SIM-PHONE-929-00000008,SIM-ACCOUNT-000017,WealthCore
8,SC-000000009,CL00000009,SIM-ID-0929-000000009,Thandi,Sithole,1977-09-21 00:00:00,Unknown,Limpopo,thandi.sithole.9@example.invalid,SIM-PHONE-929-00000009,SIM-ACCOUNT-000071,MergedBook
9,SC-000000010,CL00000010,SIM-ID-0929-000000010,Lerato,Maseko,1953-06-01 00:00:00,Male,Free State,lerato.maseko.10@example.invalid,SIM-PHONE-929-00000010,SIM-ACCOUNT-000021,LegacyLifeA

In [96]:
profiling = clients.nunique().reset_index()
profiling.columns = ["Column", "Distinct_Values"]
profiling

                      Column  Distinct_Values
0              source_row_id            12000
1                  client_id            12000
2        synthetic_id_number            11683
3                 first_name               24
4                  last_name               20
5              date_of_birth             9969
6                     gender                7
7                   province               12
8                      email            12000
9          phone_placeholder            12000
10  bank_account_placeholder              100
11             source_system                4

In [97]:
clients.isnull().sum()

source_row_id                 0
client_id                     0
synthetic_id_number         168
first_name                    0
last_name                     0
date_of_birth                38
gender                      276
province                    245
email                         0
phone_placeholder             0
bank_account_placeholder      0
source_system                 0
dtype: int64

In [98]:
clients.duplicated().sum()

np.int64(0)

In [99]:
clients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   source_row_id             12000 non-null  object
 1   client_id                 12000 non-null  object
 2   synthetic_id_number       11832 non-null  object
 3   first_name                12000 non-null  object
 4   last_name                 12000 non-null  object
 5   date_of_birth             11962 non-null  object
 6   gender                    11724 non-null  object
 7   province                  11755 non-null  object
 8   email                     12000 non-null  object
 9   phone_placeholder         12000 non-null  object
 10  bank_account_placeholder  12000 non-null  object
 11  source_system             12000 non-null  object
dtypes: object(12)
memory usage: 1.1+ MB

In [100]:
#Checking for consistency.
clients['province'].value_counts().head(20)

province
Western cape     1018
Western Cape     1013
KwaZulu-Natal     997
Limpopo           997
Free State        994
Gauteng           989
Northern Cape     975
Mpumalanga        965
North West        964
KZN               961
Eastern Cape      947
gauteng           935
Name: count, dtype: int64

In [101]:
clients['province'].unique()

array(['Western Cape', 'KwaZulu-Natal', 'Limpopo', 'Western cape',
       'gauteng', 'Northern Cape', 'Free State', 'KZN', 'Eastern Cape',
       'North West', 'Gauteng', 'Mpumalanga', nan], dtype=object)

# CLEANING DATASETS

In [102]:
policy = pd.read_csv("../raw_data/sanlam_raw_policies.csv")
clients = pd.read_excel("../raw_data/sanlam_raw_clients.csv.xlsx")

In [103]:
policy.head(5)

,source_row_id,policy_id,client_id,advisor_id,product_code,product_line,inception_date,end_date,annual_premium,sum_assured,policy_status,currency,source_system
0,SP-000000001,POL000000001,MISSING-763321,ADV000276,WEALTH,Wealth Investment,05/06/2022,04/06/2027,33254.23,"6.578.229,57",In Force,ZAR,WealthCore
1,SP-000000002,POL000000002,CL00011475,ADV000543,RA,Retirement Annuity,2021-09-05,2031/09/03,"ZAR 40,947.57","9,867,321.34",Lapsed,ZAR,WealthCore
2,SP-000000003,POL000000003,CL00004560,ADV000245,LIFE,Life Cover,2021/07/11,07-10-2026,46022.97,"R 7,841,284.09",In Force,ZAR,WealthCore
3,SP-000000004,POL000000004,CL00010896,ADV000588,WEALTH,Wealth Investment,07-23-2023,2033/07/20,"38.998,85","1,450,285.20",Unknown,R,LegacyLifeA
4,SP-000000005,POL000000005,CL00011016,ADV000019,RA,Retirement Annuity,2020-06-16,06-16-2021,"ZAR 21,239.96","R 1,396,051.35",Unknown,zar,WealthCore

In [104]:
policy.dtypes

source_row_id     object
policy_id         object
client_id         object
advisor_id        object
product_code      object
product_line      object
inception_date    object
end_date          object
annual_premium    object
sum_assured       object
policy_status     object
currency          object
source_system     object
dtype: object

In [105]:
pd.DataFrame({
    'Column': policy.columns,
    'Data Type': policy.dtypes,
    'Non Null Count': policy.count().values,
    'Null Count': policy.isnull().sum().values
})

                        Column Data Type  Non Null Count  Null Count
source_row_id    source_row_id    object           26000           0
policy_id            policy_id    object           26000           0
client_id            client_id    object           26000           0
advisor_id          advisor_id    object           26000           0
product_code      product_code    object           26000           0
product_line      product_line    object           26000           0
inception_date  inception_date    object           25919          81
end_date              end_date    object           25948          52
annual_premium  annual_premium    object           25901          99
sum_assured        sum_assured    object           25928          72
policy_status    policy_status    object           26000           0
currency              currency    object           26000           0
source_system    source_system    object           26000           0

In [106]:
missing_inception_date = policy[
    policy['inception_date'].isna() |
    policy['inception_date'].astype(str).str.strip().eq('')
].copy()

missing_inception_date

,source_row_id,policy_id,client_id,advisor_id,product_code,product_line,inception_date,end_date,annual_premium,sum_assured,policy_status,currency,source_system
77,SP-000000078,POL000000078,CL00011151,ADV000533,RA,Retirement Annuity,NaN,03-21-2022,"ZAR 3,504.47",7198973.95,Active,R,LegacyLifeB
154,SP-000000155,POL000000155,CL00008433,ADV000148,LIFE,Life Cover,NaN,10-25-2023,"R 46,636.39","R 3,513,263.75",In Force,ZAR,LegacyLifeA
663,SP-000000664,POL000000664,CL00000561,ADV000568,LIFE,Life Cover,NaN,10-14-2023,"11.865,55","1.075.819,21",In Force,R,WealthCore
1476,SP-000001477,POL000001477,CL00010164,ADV000284,RA,Retirement Annuity,NaN,08-02-2027,30796.60,"R 11,108,706.40",Cancelled,R,WealthCore
1528,SP-000001529,POL000001529,CL00001196,ADV000266,RA,Retirement Annuity,NaN,2031-11-02,37519.85,"1.860.457,25",Unknown,ZAR,LegacyLifeB
...,...,...,...,...,...,...,...,...,...,...,...,...,...
24555,SP-000024556,POL000024556,CL00005971,ADV000125,LIFE,Life Cover,NaN,2038-01-16,"ZAR 32,376.87","7,438,145.59",INFORCE,ZAR,WealthCore
24946,SP-000024947,POL000024947,CL00007434,ADV000356,WEALTH,Wealth Investment,NaN,2041/10/06,"10.464,66","11.806.559,47",Active,R,LegacyLifeB
25193,SP-000025194,POL000025194,CL00007834,ADV000345,LIFE,Life Cover,NaN,2024-04-19,"ZAR 16,909.22","2,126,701.87",Active,zar,LegacyLifeA
25338,SP-000025339,POL000025339,CL00009649,MISSING-655648,RA,Retirement Annuity,NaN,2030-01-24,"13.308,24",3874195.57,INFORCE,ZAR,WealthCore
25957,SP-000025958,POL000025958,CL00006898,ADV000359,LIFE,Life Cover,NaN,11-28-2026,"29.111,08","ZAR 3,726,944.04",Cancelled,R,LegacyLifeA

In [107]:
policy[policy['policy_id'].duplicated(keep=False)] \
    .sort_values('policy_id')

Empty DataFrame
Columns: [source_row_id, policy_id, client_id, advisor_id, product_code, product_line, inception_date, end_date, annual_premium, sum_assured, policy_status, currency, source_system]
Index: []

In [108]:
policy[policy['end_date'].isna()
][[
    'policy_id',
    'client_id',
    'product_code',
    'product_line',
    'end_date',
    'policy_status'
]].head(20)

,policy_id,client_id,product_code,product_line,end_date,policy_status
209,POL000000210,CL00005630,LIFE,Life Cover,NaN,INFORCE
1652,POL000001653,CL00000023,RA,Retirement Annuity,NaN,Lapsed
1881,POL000001882,CL00011589,LIFE,Life Cover,NaN,Active
2137,POL000002138,CL00005441,LIFE,Life Cover,NaN,In Force
2355,POL000002356,CL00010383,WEALTH,Wealth Investment,NaN,Unknown
3585,POL000003586,CL00003941,LIFE,Life Cover,NaN,Cancelled
3811,POL000003812,CL00005192,RA,Retirement Annuity,NaN,Cancelled
4570,POL000004571,CL00010816,RA,Retirement Annuity,NaN,Lapsed
4877,POL000004878,CL00003869,LIFE,Life Cover,NaN,Cancelled
5154,POL000005155,CL00005973,WEALTH,Wealth Investment,NaN,Cancelled
5286,POL000005287,CL00009073,LIFE,Life Cover,NaN,INFORCE
5409,POL000005410,CL00004359,RA,Retirement Annuity,NaN,Unknown
6224,POL000006225,CL00010318,LIFE,Life Cover,NaN,In Force
6258,POL000006259,CL00001811,WEALTH,Wealth Investment,NaN,In Force
6285,POL000006286,CL00011434,RA,Retirement Annuity,NaN,In Force
6591,POL000006592,CL00005432,LIFE,Life Cover,NaN,Active
6924,POL000006925,CL00004034,LIFE,LIFE COVER,NaN,Unknown
7279,POL000007280,CL00000987,LIFE,Life Cover,NaN,INFORCE
7306,POL000007307,CL00000404,LIFE,Life Cover,NaN,In Force
7813,POL000007814,CL00001007,LIFE,Life Cover,NaN,In Force

In [109]:
missing_ids = policy.loc[
    policy['inception_date'].isna(),
    'policy_id'
]
policy[
    policy['policy_id'].isin(missing_ids)
].sort_values('policy_id').head(10)

,source_row_id,policy_id,client_id,advisor_id,product_code,product_line,inception_date,end_date,annual_premium,sum_assured,policy_status,currency,source_system
77,SP-000000078,POL000000078,CL00011151,ADV000533,RA,Retirement Annuity,NaN,03-21-2022,"ZAR 3,504.47",7198973.95,Active,R,LegacyLifeB
154,SP-000000155,POL000000155,CL00008433,ADV000148,LIFE,Life Cover,NaN,10-25-2023,"R 46,636.39","R 3,513,263.75",In Force,ZAR,LegacyLifeA
663,SP-000000664,POL000000664,CL00000561,ADV000568,LIFE,Life Cover,NaN,10-14-2023,"11.865,55","1.075.819,21",In Force,R,WealthCore
1476,SP-000001477,POL000001477,CL00010164,ADV000284,RA,Retirement Annuity,NaN,08-02-2027,30796.60,"R 11,108,706.40",Cancelled,R,WealthCore
1528,SP-000001529,POL000001529,CL00001196,ADV000266,RA,Retirement Annuity,NaN,2031-11-02,37519.85,"1.860.457,25",Unknown,ZAR,LegacyLifeB
2281,SP-000002282,POL000002282,CL00000756,ADV000056,RA,Retirement Annuity,NaN,24/10/2027,"ZAR 38,268.13","421,924.73",INFORCE,R,LegacyLifeA
2351,SP-000002352,POL000002352,CL00009346,ADV000236,LIFE,Life Cover,NaN,09-07-2033,"R 12,299.61","ZAR 11,362,691.07",Lapsed,ZAR,WealthCore
2432,SP-000002433,POL000002433,CL00004877,ADV000122,LIFE,Life Cover,NaN,05/03/2041,"ZAR 7,338.86","ZAR 3,582,457.06",Cancelled,ZAR,LegacyLifeA
3778,SP-000003779,POL000003779,CL00003661,MISSING-102979,WEALTH,Wealth Investment,NaN,31/05/2022,"R 35,936.00","10.936.360,16",In Force,ZAR,LegacyLifeB
3839,SP-000003840,POL000003840,CL00001401,ADV000331,RA,Retirement Annuity,NaN,2020/09/24,"R 33,059.68",7745645.58,Lapsed,zar,WealthCore

In [110]:
# quarantine = policy[
#     policy['inception_date'].isna()
# ].copy()

# quarantine['quarantine_reason'] = (
#     'Missing inception_date'
# )  be back after cleaning.....

In [111]:
# #Removing quarantined records.
# policy_clean = policy[
#     policy['inception_date'].notna()
# ].copy()

In [112]:
# policy_clean.to_csv(
#     '../clean_data/policies_clean.csv',
#     index=False
# )

# quarantine.to_csv(
#     '../quarantine/inception_date_quarantine.csv',
#     index=False
# )

In [113]:
# quarantine = pd.read_csv("../quarantine/inception_date_quarantine.csv")
# quarantine

In [114]:
missing_end_date = policy[
    policy['end_date'].isna() |
    policy['end_date'].astype(str).str.strip().eq('')
].copy()

missing_end_date

,source_row_id,policy_id,client_id,advisor_id,product_code,product_line,inception_date,end_date,annual_premium,sum_assured,policy_status,currency,source_system
209,SP-000000210,POL000000210,CL00005630,ADV000212,LIFE,Life Cover,2020-04-15,NaN,46468.57,2325252.22,INFORCE,R,WealthCore
1652,SP-000001653,POL000001653,CL00000023,ADV000223,RA,Retirement Annuity,2024-07-01,NaN,"R 30,719.53",4547308.28,Lapsed,R,LegacyLifeA
1881,SP-000001882,POL000001882,CL00011589,ADV000141,LIFE,Life Cover,02-10-2021,NaN,"24,094.47","10,176,435.17",Active,zar,LegacyLifeA
2137,SP-000002138,POL000002138,CL00005441,ADV000434,LIFE,Life Cover,2018/05/30,NaN,"R 24,145.48","1,853,687.80",In Force,ZAR,LegacyLifeA
2355,SP-000002356,POL000002356,CL00010383,ADV000037,WEALTH,Wealth Investment,29/02/2020,NaN,"43,043.29","10.525.734,78",Unknown,R,LegacyLifeB
3585,SP-000003586,POL000003586,CL00003941,MISSING-644473,LIFE,Life Cover,2023/09/24,NaN,"ZAR 35,775.70","ZAR 7,125,555.90",Cancelled,zar,LegacyLifeA
3811,SP-000003812,POL000003812,CL00005192,ADV000538,RA,Retirement Annuity,2024/01/11,NaN,"31,663.05","ZAR 1,447,054.05",Cancelled,zar,WealthCore
4570,SP-000004571,POL000004571,CL00010816,ADV000220,RA,Retirement Annuity,10-25-2021,NaN,"R 18,302.89","ZAR 1,790,540.16",Lapsed,ZAR,LegacyLifeA
4877,SP-000004878,POL000004878,CL00003869,ADV000551,LIFE,Life Cover,2022/03/22,NaN,"R 21,518.11","R 7,269,314.43",Cancelled,R,LegacyLifeA
5154,SP-000005155,POL000005155,CL00005973,ADV000037,WEALTH,Wealth Investment,18/09/2025,NaN,"R 29,361.47","ZAR 11,979,744.91",Cancelled,zar,WealthCore
5286,SP-000005287,POL000005287,CL00009073,ADV000356,LIFE,Life Cover,11-29-2020,NaN,9376.93,"10.544.324,42",INFORCE,zar,LegacyLifeB
5409,SP-000005410,POL000005410,CL00004359,ADV000444,RA,Retirement Annuity,13/07/2023,NaN,28638.52,9964766.29,Unknown,zar,LegacyLifeA
6224,SP-000006225,POL000006225,CL00010318,ADV000472,LIFE,Life Cover,06-09-2019,NaN,"46.517,65","ZAR 9,916,984.77",In Force,ZAR,WealthCore
6258,SP-000006259,POL000006259,CL00001811,ADV000340,WEALTH,Wealth Investment,2017/05/08,NaN,"11,919.68","10,786,424.14",In Force,ZAR,WealthCore
6285,SP-000006286,POL000006286,CL00011434,ADV000311,RA,Retirement Annuity,09/06/2017,NaN,35180.65,"452.101,53",In Force,zar,LegacyLifeA
6591,SP-000006592,POL000006592,CL00005432,ADV000028,LIFE,Life Cover,06/05/2025,NaN,"13,276.51","R 7,924,279.71",Active,ZAR,WealthCore
6924,SP-000006925,POL000006925,CL00004034,ADV000320,LIFE,LIFE COVER,03-13-2021,NaN,"R 32,599.87","11,236,082.49",Unknown,ZAR,LegacyLifeB
7279,SP-000007280,POL000007280,CL00000987,ADV000228,LIFE,Life Cover,14/07/2025,NaN,"9.229,35","8,753,923.19",INFORCE,ZAR,LegacyLifeB
7306,SP-000007307,POL000007307,CL00000404,ADV000318,LIFE,Life Cover,2023/12/13,NaN,"R 2,552.75","6.300.992,85",In Force,zar,LegacyLifeB
7813,SP-000007814,POL000007814,CL00001007,ADV000423,LIFE,Life Cover,11-30-2023,NaN,"42.570,74","ZAR 2,272,434.00",In Force,R,WealthCore
8255,SP-000008256,POL000008256,CL00008229,ADV000487,WEALTH,Wealth Investment,04-21-2019,NaN,"ZAR 30,538.18",3944131.35,In Force,R,WealthCore
10096,SP-000010097,POL000010097,CL00009524,ADV000599,WEALTH,Wealth Investment,2022/09/04,NaN,"21,233.44","R 1,842,856.07",Lapsed,R,LegacyLifeB
11515,SP-000011516,POL000011516,CL00003205,ADV000171,LIFE,Life Cover,02/05/2024,NaN,"R 14,546.78",11593210.64,Lapsed,zar,LegacyLifeB
11836,SP-000011837,POL000011837,CL00003967,ADV000239,LIFE,Life Cover,2022/02/03,NaN,"1.376,58",8370096.11,In Force,zar,LegacyLifeA
12118,SP-000012119,POL000012119,CL00008266,ADV000271,WEALTH,Wealth Investment,16/04/2020,NaN,"31.518,83","10,847,235.28",Unknown,R,WealthCore
13136,SP-000013137,POL000013137,CL00007314,ADV000120,WEALTH,Wealth Investment,07-27-2019,NaN,"ZAR 22,216.61","11,532,309.86",Lapsed,ZAR,LegacyLifeB
13509,SP-000013510,POL000013510,CL00000097,ADV000197,WEALTH,Wealth Investment,01-24-2018,NaN,"R 11,363.73",NaN,Active,ZAR,WealthCore
13645,SP-000013646,POL000013646,CL00006448,ADV000436,RA,Retirement Annuity,2022-01-27,NaN,"R 2,140.61","R 8,588,115.58",Unknown,R,LegacyLifeA
14803,SP-000014804,POL000014804,CL00010665,ADV000042,WEALTH,Wealth Investment,05-29-2019,NaN,"R 2,302.40",9127057.43,Cancelled,ZAR,WealthCore
15089,SP-000015090,POL000015090,CL00000596,ADV000361,WEALTH,Wealth Investment,2023/07/06,NaN,"391,64",9955723.38,INFORCE,zar,LegacyLifeB
16817,SP-000016818,POL000016818,CL00011963,ADV000268,RA,Retirement Annuity,06-30-2022,NaN,"18.237,17","ZAR 3,140,054.61",In Force,ZAR,WealthCore
16881,SP-000016882,POL000016882,CL00010168,ADV000053,WEALTH,Wealth Investment,05/03/2017,NaN,"R 22,706.99","11,038,884.13",Cancelled,R,LegacyLifeB
16894,SP-000016895,POL000016895,CL00009383,ADV000189,RA,Retirement Annuity,10/08/2021,NaN,"47,951.29",9693122.73,Unknown,R,WealthCore
17119,SP-000017120,POL000017120,CL00006580,ADV000521,WEALTH,Wealth Investment,2018-09-05,NaN,"R 21,933.35","R 2,825,536.18",Unknown,R,LegacyLifeB
17266,SP-000017267,POL000017267,CL00007214,ADV000362,RA,Retirement Annuity,2022/10/06,NaN,"ZAR 32,229.35","ZAR 3,660,655.43",INFORCE,R,WealthCore
17657,SP-000017658,POL000017658,CL00001759,ADV000047,LIFE,Life Cover,05-22-2022,NaN,"ZAR 42,926.43",6655862.72,INFORCE,zar,LegacyLifeB
18533,SP-000018534,POL000018534,CL00009861,ADV000321,LIFE,Life Cover,07-23-2023,NaN,"3.294,27",1211036.14,Unknown,ZAR,LegacyLifeB
21030,SP-000021031,POL000021031,CL00010777,MISSING-440899,RA,Retirement Annuity,2021-10-22,NaN,"ZAR 5,418.37","8,314,633.72",In Force,R,LegacyLifeB
21194,SP-000021195,POL000021195,CL00006945,ADV000035,WEALTH,Wealth Investment,2022-02-19,NaN,"20.114,86",11309369.95,Cancelled,zar,WealthCore
21244,SP-000021245,POL000021245,CL00003831,ADV000592,RA,Retirement Annuity,2018-06-03,NaN,35265.06,"R 7,909,507.83",Lapsed,ZAR,LegacyLifeB
21373,SP-000021374,POL000021374,CL00006451,ADV000478,LIFE,Life Cover,2023/09/05,NaN,"ZAR 34,568.07","ZAR 2,795,885.42",INFORCE,ZAR,LegacyLifeA
21491,SP-000021492,POL000021492,CL00001310,ADV000454,RA,Retirement Annuity,03-29-2020,NaN,"38,641.05","ZAR 4,067,898.26",Unknown,ZAR,WealthCore
22470,SP-000022471,POL000022471,CL00002456,ADV000035,WEALTH,Wealth Investment,2021-06-22,NaN,"33,752.24","4.891.148,57",Cancelled,ZAR,LegacyLifeA
22500,SP-000022501,POL000022501,CL00007932,ADV000004,RA,Retirement Annuity,11/03/2019,NaN,"28.053,13","ZAR 9,859,621.57",Cancelled,ZAR,LegacyLifeB
22528,SP-000022529,POL000022529,CL00002893,ADV000477,LIFE,Life Cover,09-27-2021,NaN,28110.92,"R 4,549,106.02",Cancelled,ZAR,LegacyLifeB
22699,SP-000022700,POL000022700,CL00006795,ADV000516,LIFE,Life Cover,09/06/2020,NaN,"R 29,775.95","779,973.06",Unknown,R,LegacyLifeA
23358,SP-000023359,POL000023359,CL00006740,ADV000332,LIFE,Life Cover,2023/04/26,NaN,24953.18,"ZAR 629,230.08",In Force,ZAR,WealthCore
23514,SP-000023515,POL000023515,CL00004155,ADV000320,RA,Retirement Annuity,22/09/2023,NaN,7233.06,"8.243.855,43",In Force,zar,LegacyLifeA
23937,SP-000023938,POL000023938,CL00007394,ADV000202,WEALTH,Wealth Investment,2021-11-24,NaN,"R 12,121.84","R 11,955,677.47",In Force,ZAR,LegacyLifeB
24909,SP-000024910,POL000024910,CL00002211,ADV000431,RA,Retirement Annuity,14/05/2018,NaN,"ZAR 26,651.66","5.161.129,99",Cancelled,zar,LegacyLifeA
25121,SP-000025122,POL000025122,CL00006410,ADV000393,WEALTH,Wealth Investment,04/08/2020,NaN,"12,731.44","6.559.536,20",In Force,ZAR,WealthCore
25264,SP-000025265,POL000025265,CL00006455,ADV000110,WEALTH,Wealth Investment,2025-06-09,NaN,"25.164,96",699304.37,Active,zar,WealthCore

In [115]:
policy[
    policy['end_date'].isna()
]['policy_status'].value_counts(dropna=False)

policy_status
In Force     14
Cancelled    11
Unknown      10
INFORCE       7
Lapsed        6
Active        4
Name: count, dtype: int64

In [116]:
policy['policy_status'] = (
    policy['policy_status']
    .astype('string')
    .str.strip()
    .replace({
        'INFORCE': 'In Force'
    })
)

In [117]:
policy.head(5)

,source_row_id,policy_id,client_id,advisor_id,product_code,product_line,inception_date,end_date,annual_premium,sum_assured,policy_status,currency,source_system
0,SP-000000001,POL000000001,MISSING-763321,ADV000276,WEALTH,Wealth Investment,05/06/2022,04/06/2027,33254.23,"6.578.229,57",In Force,ZAR,WealthCore
1,SP-000000002,POL000000002,CL00011475,ADV000543,RA,Retirement Annuity,2021-09-05,2031/09/03,"ZAR 40,947.57","9,867,321.34",Lapsed,ZAR,WealthCore
2,SP-000000003,POL000000003,CL00004560,ADV000245,LIFE,Life Cover,2021/07/11,07-10-2026,46022.97,"R 7,841,284.09",In Force,ZAR,WealthCore
3,SP-000000004,POL000000004,CL00010896,ADV000588,WEALTH,Wealth Investment,07-23-2023,2033/07/20,"38.998,85","1,450,285.20",Unknown,R,LegacyLifeA
4,SP-000000005,POL000000005,CL00011016,ADV000019,RA,Retirement Annuity,2020-06-16,06-16-2021,"ZAR 21,239.96","R 1,396,051.35",Unknown,zar,WealthCore

In [118]:
policy['annual_premium'].unique()

array(['33254.23', 'ZAR 40,947.57', '46022.97', ..., '1989.51',
       '29,920.76', 'R 20,639.85'], shape=(25781,), dtype=object)

In [119]:
policy['annual_premium'].isna().sum()

np.int64(99)

In [120]:
policy['product_line'].unique()

array(['Wealth Investment', 'Retirement Annuity', 'Life Cover',
       'Wealth Invest.', 'LIFE COVER', 'Retirement annuity'], dtype=object)

In [121]:
# Standardising
policy['product_line'] = (
    policy['product_line']
    .str.strip()
    .replace({
        'Wealth Invest.': 'Wealth Investment',
        'LIFE COVER': 'Life Cover',
        'Retirement annuity': 'Retirement Annuity'
    })
)

In [122]:
missing_annual_premium= policy[
    policy['annual_premium'].isna() |
    policy['annual_premium'].astype(str).str.strip().eq('')
].copy()

missing_annual_premium

,source_row_id,policy_id,client_id,advisor_id,product_code,product_line,inception_date,end_date,annual_premium,sum_assured,policy_status,currency,source_system
518,SP-000000519,POL000000519,CL00002085,ADV000400,WEALTH,Wealth Investment,26/08/2023,2024-08-25,NaN,"10.067.434,45",In Force,ZAR,LegacyLifeA
597,SP-000000598,POL000000598,CL00011952,ADV000330,LIFE,Life Cover,05-27-2021,05-27-2022,NaN,"1,045,199.68",In Force,ZAR,LegacyLifeB
943,SP-000000944,POL000000944,CL00003267,ADV000550,RA,Retirement Annuity,05-06-2024,05-06-2025,NaN,10825277.05,Unknown,ZAR,LegacyLifeB
1425,SP-000001426,POL000001426,CL00009165,ADV000256,WEALTH,Wealth Investment,2020/10/31,29/10/2030,NaN,7569873.01,Cancelled,ZAR,WealthCore
1432,SP-000001433,POL000001433,CL00009801,ADV000183,WEALTH,Wealth Investment,22/06/2025,20/06/2035,NaN,"R 2,304,997.32",In Force,ZAR,LegacyLifeA
...,...,...,...,...,...,...,...,...,...,...,...,...,...
24642,SP-000024643,POL000024643,MISSING-641100,ADV000166,LIFE,Life Cover,25/03/2017,2018-03-25,NaN,"3,268,828.23",Unknown,zar,WealthCore
24778,SP-000024779,POL000024779,CL00004585,ADV000172,LIFE,Life Cover,08-26-2019,08-21-2039,NaN,"5.088.340,55",Active,ZAR,WealthCore
24859,SP-000024860,POL000024860,CL00000770,ADV000446,RA,Retirement Annuity,09-21-2022,09-21-2023,NaN,"R 2,450,241.88",Cancelled,zar,LegacyLifeB
25446,SP-000025447,POL000025447,CL00002630,ADV000561,WEALTH,Wealth Investment,17/12/2017,12/12/2037,NaN,"ZAR 5,689,893.28",Lapsed,zar,WealthCore
25890,SP-000025891,POL000025891,CL00009585,ADV000385,RA,Retirement Annuity,06-29-2017,06-24-2037,NaN,"ZAR 4,085,469.36",Lapsed,ZAR,LegacyLifeA

In [123]:
policy['inception_date'].dropna().head(10)

0    05/06/2022
1    2021-09-05
2    2021/07/11
3    07-23-2023
4    2020-06-16
5    11-06-2022
6    2019/03/15
7    18/06/2022
8    2022-06-16
9    11-17-2022
Name: inception_date, dtype: object

In [124]:
policy.dtypes

source_row_id             object
policy_id                 object
client_id                 object
advisor_id                object
product_code              object
product_line              object
inception_date            object
end_date                  object
annual_premium            object
sum_assured               object
policy_status     string[python]
currency                  object
source_system             object
dtype: object

In [125]:
policy.isnull().sum()

source_row_id      0
policy_id          0
client_id          0
advisor_id         0
product_code       0
product_line       0
inception_date    81
end_date          52
annual_premium    99
sum_assured       72
policy_status      0
currency           0
source_system      0
dtype: int64

In [126]:
# #Changing datatype
# policy['inception_date'] = pd.to_datetime(
#     policy['inception_date'],
#     errors='coerce'
# )
# policy[policy['inception_date'].isna()]

In [127]:
# policy['inception_date'] = pd.to_datetime(
#     policy['inception_date'],
#     errors='coerce',
#     format='mixed'
# )

# policy['end_date'] = pd.to_datetime(
#     policy['end_date'],
#     errors='coerce',
#     format='mixed'
# )

In [128]:
policy[policy['annual_premium'].isna()][
    ['source_row_id', 'policy_id', 'annual_premium']
].head(10)

     source_row_id     policy_id annual_premium
518   SP-000000519  POL000000519            NaN
597   SP-000000598  POL000000598            NaN
943   SP-000000944  POL000000944            NaN
1425  SP-000001426  POL000001426            NaN
1432  SP-000001433  POL000001433            NaN
1639  SP-000001640  POL000001640            NaN
1695  SP-000001696  POL000001696            NaN
1891  SP-000001892  POL000001892            NaN
2157  SP-000002158  POL000002158            NaN
2193  SP-000002194  POL000002194            NaN

In [129]:
policy['annual_premium'].isna().sum()

np.int64(99)

In [130]:
policy.loc[
    policy['annual_premium'].isna(),
    ['annual_premium', 'sum_assured']
].head(10)

     annual_premium       sum_assured
518             NaN     10.067.434,45
597             NaN      1,045,199.68
943             NaN       10825277.05
1425            NaN        7569873.01
1432            NaN    R 2,304,997.32
1639            NaN        7078072.47
1695            NaN    R 9,324,972.68
1891            NaN      5.716.340,82
2157            NaN        8046906.00
2193            NaN  ZAR 7,068,064.05

In [131]:
policy['currency'] = (
    policy['currency']
    .astype('string')
    .str.strip()
    .str.upper()
    .replace({
        'R': 'ZAR'
    })
)

In [132]:
policy['currency'].unique()

<StringArray>
['ZAR']
Length: 1, dtype: string

In [133]:
policy['annual_premium'].value_counts(dropna=False)

annual_premium
NaN             99
R --            59
not recorded    52
10.341,40        2
23,341.21        2
                ..
28.149,60        1
21.404,83        1
19,291.08        1
1,355.10         1
ZAR 5,141.26     1
Name: count, Length: 25781, dtype: int64

In [134]:
policy['annual_premium'] = policy['annual_premium'].replace({
    'R --': pd.NA,
    'not recorded': pd.NA
})

In [135]:
policy['annual_premium'] = (
    policy['annual_premium']
    .str.replace('ZAR', '', regex=False)
    .str.replace('R', '', regex=False)
    .str.strip()
)

In [136]:
policy['annual_premium'].value_counts().tail(20)

annual_premium
19,069.24    1
39,791.15    1
17.669,62    1
22,738.33    1
25,634.43    1
2,032.06     1
17,116.27    1
32,775.68    1
9,278.10     1
30281.21     1
34624.58     1
15,126.60    1
9.589,98     1
43889.14     1
37,533.29    1
5,141.26     1
6.204,89     1
41,997.91    1
4,573.36     1
20,639.85    1
Name: count, dtype: int64

In [137]:
policy.tail(10)

,source_row_id,policy_id,client_id,advisor_id,product_code,product_line,inception_date,end_date,annual_premium,sum_assured,policy_status,currency,source_system
25990,SP-000025991,POL000025991,CL00003902,ADV000514,WEALTH,Wealth Investment,12-22-2023,2043/12/17,"17,017.33",10343175.07,Lapsed,ZAR,LegacyLifeA
25991,SP-000025992,POL000025992,CL00010114,ADV000499,RA,Retirement Annuity,2021-04-15,2022-04-15,101.93,"ZAR 6,857,004.92",Cancelled,ZAR,LegacyLifeA
25992,SP-000025993,POL000025993,CL00003128,ADV000259,LIFE,Life Cover,2020-06-28,06-27-2025,"42,019.15","ZAR 8,845,653.36",In Force,ZAR,WealthCore
25993,SP-000025994,POL000025994,CL00010312,ADV000015,RA,Retirement Annuity,2020-01-13,11/01/2025,"35.029,02","ZAR 10,461,607.81",In Force,ZAR,WealthCore
25994,SP-000025995,POL000025995,CL00002243,ADV000353,LIFE,Life Cover,05-05-2020,05/05/2021,"20,700.51","R 11,323,884.58",Lapsed,ZAR,LegacyLifeB
25995,SP-000025996,POL000025996,CL00002936,ADV000505,WEALTH,Wealth Investment,10-01-2023,2028/09/29,"21,683.36",8034451.76,Unknown,ZAR,WealthCore
25996,SP-000025997,POL000025997,CL00011530,ADV000197,WEALTH,Wealth Investment,25/03/2023,20/03/2043,"35,300.77","R 888,611.77",Cancelled,ZAR,LegacyLifeB
25997,SP-000025998,POL000025998,CL00000633,ADV000587,LIFE,Life Cover,04/01/2020,01-02-2025,1989.51,9690765.13,Unknown,ZAR,LegacyLifeB
25998,SP-000025999,POL000025999,CL00006256,ADV000003,RA,Retirement Annuity,2021/01/24,01-24-2022,"29,920.76",5595002.02,Active,ZAR,WealthCore
25999,SP-000026000,POL000026000,MISSING-506749,ADV000486,RA,Retirement Annuity,2019/12/03,12-01-2024,"20,639.85","1,568,769.22",In Force,ZAR,LegacyLifeA

In [138]:
policy['annual_premium'].str.contains(r'\.\d{3},\d{2}', na=False).sum()

np.int64(5100)

In [139]:
#Fixing money format
mask = policy['annual_premium'].str.contains(
    r'\.\d{3},\d{2}', na=False
)

policy.loc[mask, 'annual_premium'] = (
    policy.loc[mask, 'annual_premium']
    .str.replace('.', '', regex=False)
    .str.replace(',', '.', regex=False)
)

policy['annual_premium'] = (
    policy['annual_premium']
    .str.replace(',', '', regex=False)
)

In [140]:
policy.isna().sum()

source_row_id       0
policy_id           0
client_id           0
advisor_id          0
product_code        0
product_line        0
inception_date     81
end_date           52
annual_premium    210
sum_assured        72
policy_status       0
currency            0
source_system       0
dtype: int64

In [141]:
policy['annual_premium'] = pd.to_numeric(
    policy['annual_premium'],
    errors='coerce'
)

In [142]:
policy.dtypes

source_row_id             object
policy_id                 object
client_id                 object
advisor_id                object
product_code              object
product_line              object
inception_date            object
end_date                  object
annual_premium           float64
sum_assured               object
policy_status     string[python]
currency          string[python]
source_system             object
dtype: object

In [143]:
policy['sum_assured'].value_counts(dropna=False)

sum_assured
NaN                 72
R --                41
not recorded        37
5.226.636,62         1
3,472,995.45         1
                    ..
ZAR 4,802,583.10     1
ZAR 3,823,747.35     1
6788143.33           1
ZAR 1,347,621.99     1
10,957,534.54        1
Name: count, Length: 25853, dtype: int64

In [144]:
policy['sum_assured'] = policy['sum_assured'].replace({
    'R --': pd.NA,
    'not recorded': pd.NA
})

In [145]:
policy['sum_assured'] = (
    policy['sum_assured']
    .str.replace('ZAR', '', regex=False)
    .str.replace('R', '', regex=False)
    .str.strip()
)

In [146]:
policy['sum_assured'].value_counts().tail(10)

sum_assured
8337835.48       1
11.897.324,23    1
8138517.80       1
3,929,959.06     1
340,713.02       1
11,054,830.11    1
4,099,659.44     1
4,090,131.87     1
752.044,83       1
11,667,700.70    1
Name: count, dtype: int64

In [147]:
policy['sum_assured'].str.contains(r'\.\d{3},\d{2}', na=False).sum()

np.int64(5143)

In [148]:
#Fixing money format
mask = policy['sum_assured'].str.contains(
    r'\.\d{3},\d{2}', na=False
)

policy.loc[mask, 'sum_assured'] = (
    policy.loc[mask, 'sum_assured']
    .str.replace('.', '', regex=False)
    .str.replace(',', '.', regex=False)
)

policy['sum_assured'] = (
    policy['sum_assured']
    .str.replace(',', '', regex=False)
)

In [149]:
policy['sum_assured'] = pd.to_numeric(
    policy['sum_assured'],
    errors='coerce'
)

In [150]:
policy[''].unique()
#Checking for successfully fixed columns

KeyError: ''

In [ ]:
#Checking for consistency.
clients['province'].value_counts().head(20)

In [ ]:
clients['province'] = clients['province'].replace({
    'Western cape': 'Western Cape',
    'gauteng': 'Gauteng',
    'KZN': 'KwaZulu-Natal'
})

In [ ]:
clients['gender'].value_counts()

In [ ]:
clients['gender'] = clients['gender'].replace({
    'female': 'Female',
    'F': 'Female',
    'MALE': 'Male',
    'M':'Male',
    'Unknown': 'Other'
})

In [ ]:
clients['source_system'].isna().sum()

In [ ]:
clients.isna().sum()

In [ ]:
clients.tail(20)

In [ ]:
policy[policy['client_id'] == 'CL00011077']

In [ ]:
policy.dtypes

In [ ]:
#Checking for duplicates.
for col in ['source_row_id', 'policy_id', 'client_id', 'advisor_id']:
    print(f"{col}: {policy[col].duplicated().sum()} duplicates")

In [ ]:
policy['policy_status'].value_counts()

In [ ]:
policy.head(10)

In [ ]:
policy['policy_status_flag'] = policy['policy_status'].eq('Unknown')

In [152]:
policy.tail(5)

,source_row_id,policy_id,client_id,advisor_id,product_code,product_line,inception_date,end_date,annual_premium,sum_assured,policy_status,currency,source_system,advisor_id_flag
25995,SP-000025996,POL000025996,CL00002936,ADV000505,WEALTH,Wealth Investment,10-01-2023,2028/09/29,21683.36,8034451.76,Unknown,ZAR,WealthCore,False
25996,SP-000025997,POL000025997,CL00011530,ADV000197,WEALTH,Wealth Investment,25/03/2023,20/03/2043,35300.77,888611.77,Cancelled,ZAR,LegacyLifeB,False
25997,SP-000025998,POL000025998,CL00000633,ADV000587,LIFE,Life Cover,04/01/2020,01-02-2025,1989.51,9690765.13,Unknown,ZAR,LegacyLifeB,False
25998,SP-000025999,POL000025999,CL00006256,ADV000003,RA,Retirement Annuity,2021/01/24,01-24-2022,29920.76,5595002.02,Active,ZAR,WealthCore,False
25999,SP-000026000,POL000026000,MISSING-506749,ADV000486,RA,Retirement Annuity,2019/12/03,12-01-2024,20639.85,1568769.22,In Force,ZAR,LegacyLifeA,False

In [ ]:
policy['advisor_id'].isna().sum()

In [ ]:
policy[policy['client_id'].str.startswith('MISSING-', na=False)]

In [ ]:
policy['client_id_flag'] = 'False'

policy.loc[
    policy['client_id'].str.startswith('MISSING-', na=False),
    'client_id_flag'
] = 'True'

In [ ]:
policy[policy['advisor_id'].str.startswith('MISSING-', na=False)]

,source_row_id,policy_id,client_id,advisor_id,product_code,product_line,inception_date,end_date,annual_premium,sum_assured,policy_status,currency,source_system,client_id_flag
60,SP-000000061,POL000000061,CL00000500,MISSING-958229,RA,Retirement Annuity,03/02/2023,2024/02/03,11325.86,11218813.25,Lapsed,ZAR,WealthCore,False
94,SP-000000095,POL000000095,CL00004852,MISSING-536829,LIFE,Life Cover,2017/08/19,2037-08-14,46493.87,3742884.83,Cancelled,ZAR,WealthCore,False
167,SP-000000168,POL000000168,CL00000183,MISSING-837953,RA,Retirement Annuity,2023-02-04,03/02/2028,17471.13,5815044.81,Cancelled,ZAR,LegacyLifeA,False
180,SP-000000181,POL000000181,CL00010389,MISSING-986618,RA,Retirement Annuity,2021/12/25,23/12/2031,35176.50,5755310.74,Unknown,ZAR,LegacyLifeA,False
221,SP-000000222,POL000000222,CL00011165,MISSING-744596,LIFE,Life Cover,2024-02-11,09/02/2029,29965.64,11979308.47,Unknown,ZAR,LegacyLifeB,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25869,SP-000025870,POL000025870,CL00006159,MISSING-653911,LIFE,Life Cover,2020/02/27,02-22-2040,46613.17,650923.64,Active,ZAR,LegacyLifeB,False
25891,SP-000025892,POL000025892,CL00007012,MISSING-373795,RA,Retirement Annuity,07-02-2019,06-30-2024,24475.06,9439741.31,Active,ZAR,LegacyLifeA,False
25898,SP-000025899,POL000025899,CL00003678,MISSING-114440,WEALTH,Wealth Investment,2020-09-05,09-03-2030,22980.76,5387033.21,In Force,ZAR,LegacyLifeB,False
25959,SP-000025960,POL000025960,CL00005221,MISSING-153699,WEALTH,Wealth Investment,01-28-2022,01-28-2023,27720.94,371281.79,In Force,ZAR,LegacyLifeB,False
25965,SP-000025966,POL000025966,CL00011675,MISSING-310432,WEALTH,Wealth Investment,2020-01-14,11/01/2030,23764.52,2180845.80,In Force,ZAR,LegacyLifeA,False

In [151]:
policy['advisor_id_flag'] = 'False'

policy.loc[
    policy['advisor_id'].str.startswith('MISSING-', na=False),
    'advisor_id_flag'
] = 'True'